[[main]]
  identifier = "about"
  name = "Our Story"
  url = "about"
  weight = 4

[[main]]
  identifier = "docs"
  name = "Docs"
  url = "docs"
  weight = 3

[[main]]
  identifier = "showcase"
  name = "Projects"
  url = "showcase"
  weight = 2

[[main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1

  [[main]]
  identifier = "slack"
  name = "#SLACK"
  url = "https://butterops.slack.com"
  weight = 5
